-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.users
(
    id character varying(250) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp without time zone,
    create_by character varying(255) COLLATE pg_catalog."default",
    update_at timestamp without time zone,
    update_by character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    date_of_birth date,
    email character varying(255) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone_no character varying(255) COLLATE pg_catalog."default",
    user_id integer,
    role_id bigint,
    work_at_id character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resource_point
(
    resource_type character varying(31) COLLATE pg_catalog."default" NOT NULL,
    id character varying(250) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp without time zone,
    create_by character varying(255) COLLATE pg_catalog."default",
    update_at timestamp without time zone,
    update_by character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    phone_no character varying(255) COLLATE pg_catalog."default",
    resource_id bigint,
    type_resource character varying(255) COLLATE pg_catalog."default",
    gathering_point_id character varying(250) COLLATE pg_catalog."default",
    transaction_id character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT resource_point_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id character varying(250) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp without time zone,
    create_by character varying(255) COLLATE pg_catalog."default",
    update_at timestamp without time zone,
    update_by character varying(255) COLLATE pg_catalog."default",
    gtgtcharge integer,
    categority integer,
    cod_charge integer,
    main_charge integer,
    order_id bigint,
    other_charge integer,
    other_receiver_charge integer,
    temp_charge integer,
    vat_charge integer,
    weight double precision,
    order_delivery_id bigint,
    receiver_id character varying(250) COLLATE pg_catalog."default",
    sender_id character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_delivery
(
    id bigint NOT NULL DEFAULT nextval('order_delivery_id_seq'::regclass),
    status integer,
    current_order_id character varying(250) COLLATE pg_catalog."default",
    from_order_id character varying(250) COLLATE pg_catalog."default",
    order_id character varying(250) COLLATE pg_catalog."default",
    to_order_id character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT order_delivery_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_tracking_history
(
    id bigint NOT NULL DEFAULT nextval('order_tracking_history_id_seq'::regclass),
    message_status character varying(255) COLLATE pg_catalog."default",
    order_id character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT order_tracking_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_context_orders
(
    order_id character varying(250) COLLATE pg_catalog."default" NOT NULL,
    context character varying(255) COLLATE pg_catalog."default",
    document_no integer,
    quantity integer,
    value integer
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fkdritgj6kx632jv721ctgq052 FOREIGN KEY (work_at_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resource_point
    ADD CONSTRAINT fk9jnb64scutu2hjekbio7d7eby FOREIGN KEY (gathering_point_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resource_point
    ADD CONSTRAINT fkcab62yp3xe14femjtmj8ec4dw FOREIGN KEY (transaction_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk4ffo5g9r5ki2o60rb4rwaqlvk FOREIGN KEY (order_delivery_id)
    REFERENCES public.order_delivery (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkcxk2p4bgaaa4cyy5prymu164p FOREIGN KEY (receiver_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkqso93wbafyypjn6h0pk8x23qf FOREIGN KEY (sender_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_delivery
    ADD CONSTRAINT fkgjjdq2ykb5fp81prvc4uj625x FOREIGN KEY (current_order_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_delivery
    ADD CONSTRAINT fkirbjamo9lfat1nrxunc8dgnc9 FOREIGN KEY (from_order_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_delivery
    ADD CONSTRAINT fkr2cry3gt8sjwt38hytc2tichf FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_delivery
    ADD CONSTRAINT fksd4ph237wiqbax9jnegrts0cb FOREIGN KEY (to_order_id)
    REFERENCES public.resource_point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_tracking_history
    ADD CONSTRAINT fko0m4g4k7rie60bx4qbei936ww FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_context_orders
    ADD CONSTRAINT fk80hm13nf211o2el4m1wwfnrwb FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

CREATE SEQUENCE users_id_seq;
CREATE SEQUENCE orders_id_seq;
CREATE SEQUENCE customers_id_seq;
CREATE SEQUENCE delivery_points_id_seq;
END;